// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB03i1vILVdArM3F3kxQjSLv1Aj6348_o0',
    appId: '1:593125340178:web:b79e0a89e94782428154cb',
    messagingSenderId: '593125340178',
    projectId: 'local-discovery-app-5c52f',
    authDomain: 'local-discovery-app-5c52f.firebaseapp.com',
    storageBucket: 'local-discovery-app-5c52f.firebasestorage.app',
    measurementId: 'G-NVZ4DJ60FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkVlF3Gy2IL0suoiRSwK6X3S8Bu3sVcRI',
    appId: '1:593125340178:android:907dcb507e0d7f5a8154cb',
    messagingSenderId: '593125340178',
    projectId: 'local-discovery-app-5c52f',
    storageBucket: 'local-discovery-app-5c52f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWcCrfsjKZyrFZqyV7QUEtCGLnFZ_LyzM',
    appId: '1:593125340178:ios:4ec4f1b9a46956d48154cb',
    messagingSenderId: '593125340178',
    projectId: 'local-discovery-app-5c52f',
    storageBucket: 'local-discovery-app-5c52f.firebasestorage.app',
    iosBundleId: 'com.chansdev.peopleDiscoveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWcCrfsjKZyrFZqyV7QUEtCGLnFZ_LyzM',
    appId: '1:593125340178:ios:4ec4f1b9a46956d48154cb',
    messagingSenderId: '593125340178',
    projectId: 'local-discovery-app-5c52f',
    storageBucket: 'local-discovery-app-5c52f.firebasestorage.app',
    iosBundleId: 'com.chansdev.peopleDiscoveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB03i1vILVdArM3F3kxQjSLv1Aj6348_o0',
    appId: '1:593125340178:web:a53d934206ae42468154cb',
    messagingSenderId: '593125340178',
    projectId: 'local-discovery-app-5c52f',
    authDomain: 'local-discovery-app-5c52f.firebaseapp.com',
    storageBucket: 'local-discovery-app-5c52f.firebasestorage.app',
    measurementId: 'G-WHYGT9Z34K',
  );
}
